[workspace]
members = [
    "src/btc-loan-platform-backend/src/loan_canister",
    "src/btc-loan-platform-backend/src/mock_ckbtc",
    "src/btc-loan-platform-backend/src/mock_iusd",
    "src/btc-loan-platform-backend/src/oracle_canister"
]
resolver = "2"

