[package]
name = "iusd_token_canister"
version = "0.1.0"
edition = "2021"

[dependencies]
candid = "0.9.1"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"
